apiVersion: v1
kind: Secret
metadata:
  name: csi-secret
  namespace: kube-system
stringData:
  accessKeyID: <you_id_key>
  secretAccessKey: <you_secret_key>
  endpoint: https://storage.yandexcloud.net
