apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otus
  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
spec:
  description: Otus Project gitops
  sourceRepos:
  - 'https://github.com/Kuber-2024-10OTUS/m1g29_repo.git'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
    name: in-cluster
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
