apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom-stub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-custom-stub
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      name: nginx-custom-stub
      labels:
        app: nginx-custom-stub
    spec:
      containers:
      - name: nginx-custom-stub
        image: custom-nginx:0.0.1
        readinessProbe:
          httpGet:
            path: /stub_status
            port: 8000
        ports:
          - containerPort: 8000
      - name: nginx-prometheus-exporter
        args:
          - "--nginx.scrape-uri=http://localhost:8000/stub_status"
        image: nginx/nginx-prometheus-exporter:1.3.0
        imagePullPolicy: Never
        ports:
          - name: metrics
            containerPort: 9113
      nodeSelector:
        monitoring: "true"
