apiVersion: v1
kind: Service
metadata:
  name: nginx-custom-stub
  labels:
    app: nginx-custom-stub
spec:
  selector:
    app: nginx-custom-stub
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
    - port: 9113
      targetPort: 9113
      name: metrics
