loki:
  storage:
    bucketNames:
      chunks: logbucket
      ruler: logbucket
      admin: log
    type: 's3'
    s3:
      endpoint: storage.yandexcloud.net
      secretAccessKey: <Your-secret-key-YC>
      accessKeyId: <Key-ID-YC>
  auth_enabled: false
  commonConfig:
    replication_factor: 1

test:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    nodeSelector:
      infra: "true"
    tolerations:
      - key: "node-role"        
        operator: "Equal"
        value: "infra"        
        effect: "NoSchedule"

singleBinary:
  replicas: 1
  nodeSelector:
    infra: "true"
  tolerations:
    - key: "node-role"        
      operator: "Equal"
      value: "infra"        
      effect: "NoSchedule"

gateway:
  nodeSelector:
    infra: "true"
  tolerations:
    - key: "node-role"        
      operator: "Equal"
      value: "infra"        
      effect: "NoSchedule"
