apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
    server {
        listen 8000;
        root /homework;
        location / {
            try_files $uri $uri/ =404;
        }
    }
