apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-role-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: monitoring
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: metrics-reader
  apiGroup: rbac.authorization.k8s.io
